# Generated by Django 2.1.4 on 2021-04-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='telefone',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
