# Generated by Django 2.1.4 on 2021-05-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_perfilaluno_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('enunciado', models.CharField(max_length=1000)),
                ('resposta', models.CharField(max_length=1000)),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
            ],
        ),
    ]
